[versions]
spigot-api = "1.20-R0.1-SNAPSHOT"
adventure-platform = "4.3.4"
adventure-text-minimessage = "4.17.0"
placeholderapi = "2.11.6"

[libraries]
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot-api" }
adventure-platform-bukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure-text-minimessage" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
